### ISSUE TITLE
Slidy run "ERROR: Please, add param 'scripts' in your pubspec.yaml"

### ISSUE THREAD

**Issue by marcuslindemannrohden** [Flutterando/slidy#240]
Hey guys, since I upgraded slidy to version 3.0.0 I haven't been able to use the command "slidy run <script>" anymore.
Every time that I try, I get the error: **ERROR: Please, add param 'scripts' in your pubspec.yaml** but I do have the scripts section on my pubspec.

```
vars:
  runner: flutter pub run build_runner
  clean: flutter clean
  get: flutter pub get

scripts:
  mobxwatch: $clean & $get & $runner watch --delete-conflicting-outputs
```

**Comment by edukmattos** [comment]
Hi, Marcus !
I had this problem too.
I had the spacing in relation to the left in the wrong way.
I fixed it and it is now working perfectly.

**Comment by JacquesMarques** [comment]
Me too. And I can't create a page with slidy g p modules/page/page

**Comment by marcuslindemannrohden** [comment]
@edukmattos I have tripled checked but it doesn't seem to be any indentations. 
I have tried to run it in other projects that used to work and didn't have any modifications over the last months but still happening with the same issue.

**Comment by edukmattos** [comment]
@JacquesMarques @marcuslindemannrohden I'm using a project with Flutter 2.0 and Slidy 3.0 and it's working ok

**Comment by marcuslindemannrohden** [comment]
> @JacquesMarques @marcuslindemannrohden I'm using a project with Flutter 2.0 and Slidy 3.0 and it's working ok

Hey @edukmattos, can you please double-check wich dart versions you are using?
It could be a problem caused by the last as I upgraded flutter and dart on the same day.

**Comment by jacobaraujo7** [comment]
Fixed!
